name: Deploy WordPress Theme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        ftp-server: 'your-ftp-server.com'
        ftp-username: 'your-ftp-username'
        ftp-password: 'your-ftp-password'
        local-dir: './wp-content/themes/my-theme'
        remote-dir: '/path-to-your-wordpress/wp-content/themes/my-theme'

    - name: Finalize deployment
      run: echo "Deployment complete!"
